version: '3.8'

services:
  manager:
    build: ./manager
    ports:
      - 3000:3000
    command: yarn dev -H 0.0.0.0
    tty: true

  controller:
    build: ./controller
    ports:
      - 8000:8000
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    tty: true

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    tty: true
