###
# @prompt token
POST /api/v1/prediction/models HTTP/1.1
Host: localhost:8000
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "model_name": "なす識別機v1",
    "network_name": "ResNet18",
    "param_path": "./_var/eggplant.pth",
    "labels": [
        "健常",
        "うどんこ病",
        "灰かび病",
        "すすかび病",
        "褐色円星病",
        "半身萎凋病",
        "青枯病"
    ]
}
